registry/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('registry.www.urls')),
    path('api/', include('registry.api.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

registry/www/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('elements/', views.element_list_view, name='element_list'),

    # create elements
    path('elements/create/', views.element_create_view, name='create_element'),

    # edit elements
    path('elements/<element_name>/edit/', views.element_edit_view, name='edit_element'),

    # history
    path('<login>/elements/<element_name>/history/', views.history, name='history'),

    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

registry/core/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser

from django.core import validators
from django.db import models


class CreatedUpdated(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class UserManager(BaseUserManager):
    use_in_migrations = True


class User(AbstractBaseUser, CreatedUpdated):
    """
    Our custom user
    """
    login = models.CharField(max_length=30, unique=True, null=True, validators=[validators.validate_slug])
    first_name = models.CharField(max_length=30, blank=True, null=True)
    last_name = models.CharField(max_length=30, blank=True, null=True)
    email = models.EmailField(null=True, blank=True, unique=True)

    USERNAME_FIELD = 'login'
    objects = UserManager()

    class Meta:
        db_table = 'core_user'
        managed = True


class UserElement(CreatedUpdated):
    TYPE_CHOICES = (
        ('number', 'Number'),
        ('text', 'Text'),
        ('bool', 'Bool'),
        ('gps', 'GPS'),
    )
    name = models.CharField(max_length=30, null=False, blank=False, validators=[validators.validate_slug])
    type = models.CharField(max_length=30, choices=TYPE_CHOICES, null=False, blank=False)
    description = models.CharField(max_length=128, null=True, blank=True)
    user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='elements')
    is_public = models.BooleanField(default=False)

    class Meta:
        db_table = 'core_user_elements'
        managed = True
        unique_together = ['user', 'name']


class ElementNumber(CreatedUpdated):
    """
    Stores Numeric values
    """
    value = models.FloatField(blank=False, default=0)
    comment = models.TextField(null=True, blank=True)
    user_element = models.ForeignKey('UserElement', on_delete=models.CASCADE, related_name='number_values')

    class Meta:
        db_table = 'core_element_number'
        ordering = ['-created']

    def data(self):
        return {
            'value': self.value,
        }



class ElementText(CreatedUpdated):
    """
    Stores Textual values
    """
    value = models.TextField(null=True, blank=True, default='')
    comment = models.TextField(null=True, blank=True)
    user_element = models.ForeignKey('UserElement', on_delete=models.CASCADE, related_name='text_values')

    class Meta:
        db_table = 'core_element_text'
        ordering = ['-created']

    def data(self):
        return {
            'value': self.value,
        }


class ElementBool(CreatedUpdated):
    """
    Stores Boolean values
    """
    value = models.BooleanField(null=False, blank=False)
    comment = models.TextField(null=True, blank=True)
    user_element = models.ForeignKey('UserElement', on_delete=models.CASCADE, related_name='bool_values')

    class Meta:
        db_table = 'core_element_bool'
        ordering = ['-created']

    def data(self):
        return {
            'value': self.value,
        }


class ElementGPS(CreatedUpdated):
    """
    Stores Longitude and Latitude
    """
    longitude = models.CharField(max_length=50, null=False, blank=False)
    latitude = models.CharField(max_length=50, null=False, blank=False)
    comment = models.TextField(null=True, blank=True)
    user_element = models.ForeignKey('UserElement', on_delete=models.CASCADE, related_name='gps_values')

    class Meta:
        db_table = 'core_element_gps'
        ordering = ['-created']

    def data(self):
        return {
            'longitude': self.longitude,
            'latitude': self.latitude,
        }

registry/www/models.py
from django.db import models

# Create your models here.

registry/www/forms.py
from django import forms

import registry.core.models as core_models


class CreateElementForm(forms.ModelForm):
    class Meta:
        model = core_models.UserElement
        fields = ['name', 'type', 'description', 'is_public']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name'}),
            'type': forms.Select(choices=model.TYPE_CHOICES, attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Description'}),
        }


class EditElementForm(forms.ModelForm):
    class Meta:
        model = core_models.UserElement
        fields = ['name', 'description', 'is_public']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name'}),
            'description': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Description'}),
        }


class FilterElementsForm(forms.Form):
    name = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control mb-2 mr-2', 'placeholder': 'Name or description'}))

    CHOICES = (('', 'All'),) + core_models.UserElement.TYPE_CHOICES

    type = forms.ChoiceField(required=False, choices=CHOICES,
                             widget=forms.Select(attrs={'class': 'form-control mb-2 mr-sm-2'}))


class ElementTextForm(forms.ModelForm):
    class Meta:
        model = core_models.ElementText
        fields = ['value', 'comment']
        widgets = {
            'value': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Value'}),
            'comment': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Comment'}),
        }


class ElementNumberForm(forms.ModelForm):
    class Meta:
        model = core_models.ElementNumber
        fields = ['value', 'comment']
        widgets = {
            'value': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Value'}),
            'comment': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Comment'}),
        }


class ElementBoolForm(forms.ModelForm):
    class Meta:
        model = core_models.ElementBool
        fields = ['value', 'comment']
        widgets = {
            'value': forms.Select(attrs={'class': 'form-control'}),
            'comment': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Comment'}),
        }


class ElementGPSForm(forms.ModelForm):
    class Meta:
        model = core_models.ElementGPS
        fields = ['latitude', 'longitude', 'comment']
        widgets = {
            'latitude': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Latitude'}),
            'longitude': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Longitude'}),
            'comment': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Comment'}),
        }

registry/www/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.db import IntegrityError
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404

from registry.core import models as core_models
from . import forms


@login_required(login_url='login')
def home_view(request):
    return redirect(element_list_view)


@login_required(login_url='login')
def element_list_view(request):
    context = {}

    user_elements = core_models.UserElement.objects.filter(user=request.user)

    form = forms.FilterElementsForm(request.GET or None)
    context['form'] = form

    if form.is_valid():
        search = form.cleaned_data.get('name')
        element_type = form.cleaned_data.get('type')

        if search:
            user_elements = user_elements.filter(Q(name__icontains=search) | Q(description__icontains=search))

        if element_type:
            user_elements = user_elements.filter(type=element_type)

    context['user_elements'] = user_elements

    return render(request, 'elements/element_list.html', context)


@login_required(login_url='login')
def element_create_view(request):
    context = {}
    form = forms.CreateElementForm(request.POST or None)
    if form.is_valid():
        user_element = form.save(commit=False)
        user_element.user = request.user
        try:
            user_element.save()
        except IntegrityError:
            messages.error(request, 'Element with the same name and type already exists!')
            return redirect(element_create_view)

        messages.success(request, 'Element created!')
        return redirect(element_list_view)

    context['form'] = form

    return render(request, 'elements/create_element.html', context)


@login_required(login_url='login')
def element_edit_view(request, element_name):
    context = {}
    element = get_object_or_404(core_models.UserElement, name=element_name, user=request.user)
    context['element'] = element

    form = forms.EditElementForm(instance=element)

    if request.POST:
        action = request.POST.get('action')

        if action == 'update':
            form = forms.EditElementForm(request.POST, instance=element)
            if form.is_valid():
                form.save()
                messages.success(request, 'Element updated!')
                return redirect(element_edit_view, element_name=element.name)

        elif action == 'delete':
            element.delete()
            messages.success(request, 'Element deleted!')
            return redirect(element_list_view)

    context['form'] = form

    return render(request, 'elements/edit_element.html', context)


@login_required(login_url='login')
def history(request, login, element_name):

    context = {}

    if request.user.login == login:
        element = get_object_or_404(core_models.UserElement, name=element_name, user=request.user)
    else:
        element = get_object_or_404(core_models.UserElement, name=element_name, user__login=login, is_public=True)

    models = {
        'number': core_models.ElementNumber,
        'text': core_models.ElementText,
        'bool': core_models.ElementBool,
        'gps': core_models.ElementGPS,
    }

    model = models.get(element.type)
    if not model:
        raise Http404('Unknown Element Type')

    all_history = model.objects.filter(user_element=element).order_by('-created')
    context['element'] = element

    paginator = Paginator(all_history, 30)
    page = request.GET.get('page', 1)
    context['page_objects'] = paginator.get_page(page)
    context['paginator'] = paginator

    using_forms = {
        'number': forms.ElementNumberForm,
        'text': forms.ElementTextForm,
        'bool': forms.ElementBoolForm,
        'gps': forms.ElementGPSForm,
    }

    using_form = using_forms.get(element.type)
    context['form'] = using_form()

    if request.POST:
        action = request.POST.get('action')

        if action == 'add_value':
            using_form = using_forms.get(element.type)
            form = using_form(request.POST)
            if form.is_valid():
                form.instance.user_element = element
                form.save()
                messages.success(request, 'Value added')
                return redirect(history, request.user, element.name)


    return render(request, 'elements/history.html', context)


def login_view(request):
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(home_view)
        return redirect(login_view)
    return render(request, 'login.html')


def logout_view(request):
    logout(request)
    return redirect(login_view)

registry/www/templates/elements/create_element.html
{% extends 'base.html' %}
{% block title %}Create Number Element{% endblock %}

{% block content %}
<div class="container-fluid">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}"><i class="fas fa-home"></i></a></li>
            <li class="breadcrumb-item"><a href="{% url 'element_list' %}">My Elements</a></li>
            <li class="breadcrumb-item active" aria-current="page">Create Element</li>
        </ol>
    </nav>

    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">

            <h4>Create Element</h4>

            <form method="POST">
                {% csrf_token %}
                {% include 'elements/user_element_form.html' %}

                <div class="form-group text-right">
                    <button type="submit" class="btn btn-primary form-control" name="action" value="create">Create</button>
                </div>
            </form>

        </div>
        <div class="col-md-3"></div>
    </div>


</div>
{% endblock %}

registry/www/templates/elements/delete_element_button.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-danger form-control" data-toggle="modal" data-target="#exampleModal">
    <i class="fa fa-trash"></i> Delete
</button>

<form method="post">
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you sure?
                </div>
                <div class="modal-footer">
                    <input type="hidden" value="{{ element.pk }}" name="element_id">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger" name="action" value="delete">Delete element</button>
                </div>
            </div>
        </div>
    </div>
</form>

registry/www/templates/elements/edit_element.html
{% extends 'base.html' %}
{% block title %}Edit Text Element{% endblock %}

{% block content %}
    <div class="container-fluid">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home' %}"><i class="fas fa-home"></i></a></li>
                <li class="breadcrumb-item"><a href="{% url 'element_list' %}">My Elements</a></li>
                <li class="breadcrumb-item active" aria-current="page">
                    <a href="{% url 'history' user.login element.name %}">{{ element.name }}</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Edit</li>
            </ol>
        </nav>

        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">

                <h4 class="">Edit {{ element.type|title }} Element</h4>

                <form method="POST">
                    {% csrf_token %}

                    {% include 'elements/user_element_form.html' %}

                    <div class="form-group text-right">
                        <button type="submit" class="btn btn-primary form-control" name="action" value="update">Save
                        </button>
                    </div>

                    {% include 'elements/delete_element_button.html' %}

                </form>

                <h4 class="mt-5">API URL</h4>
                <div class="text-secondary">
                        http://registry.tspoon.ru:8000/api/{{ user.login }}/elements/{{ element.name }}/<br>
                        http://registry.tspoon.ru:8000/api/{{ user.login }}/elements/{{ element.name }}/history/
                </div>

            </div>


            </div>
            <div class="col-md-3"></div>
        </div>

    </div>
{% endblock %}

registry/www/templates/elements/element_list.html
{% extends 'base.html' %}
{% block title %}My Elements{% endblock %}
{% block content %}
<div class="container-fluid">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}"><i class="fas fa-home"></i></a></li>
            <li class="breadcrumb-item active" aria-current="page">My Elements</li>
        </ol>
    </nav>

    <form method="GET" class="form-inline mb-3">
        {{ form.name }}
        {{ form.type }}

        <button type="submit" class="btn btn-secondary form-control mb-2 mr-sm-2" name="action" value="filter">Filter</button>

    </form>

    <h2>Elements
    <a href="{% url 'create_element' %}" class="btn btn-sm btn-primary float-right">
        <i class="fa fa-plus"></i> New Element
    </a>
    </h2>

    <table class="table table-borderless table-hover table-sm">
        <tbody>

        {% for element in user_elements %}
        <tr>
            <td class="pl-3">
                <a href="{% url 'history' user.login element.name %}"><strong>{{ element.name }}</strong></a>
                <span class="text-muted">| {{ element.type }}</span>
                {% if element.description %}
                    <p class="mb-0 text-secondary"><small>{{ element.description }}</small></p>
                {% endif %}
            </td>

            <td>
                <small>
                {% if element.is_public %}
                    <b class="text-success">Public</b>
                {% else %}
                    <b class="text-danger">Private</b>
                {% endif %}
            </small>
            </td>

            <td class="text-right pr-2">

                <a href="/elements/{{ element.name }}/edit/"><i class="fa fa-edit"></i></a>

            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="3" class="text-secondary text-center">
                No elements. <a href="{% url 'create_element' %}">Create!</a>
            </td>
        </tr>
        {% endfor %}

        </tbody>
    </table>

</div>

{% endblock %}

registry/www/templates/elements/history.html
{% extends 'base.html' %}

{% block title %}{{ element.name }} history {% endblock %}

{% block content %}
<div class="container-fluid">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}"><i class="fas fa-home"></i></a></li>

            {% if element.user == user %}
            <li class="breadcrumb-item"><a href="{% url 'element_list' %}">My Elements</a></li>
            {% else %}
            <li class="breadcrumb-item active">Shared elements</li>
            {% endif %}

            <li class="breadcrumb-item active" aria-current="page">{{ element.name }}</li>
            <li class="breadcrumb-item active" aria-current="page">History</li>
        </ol>
    </nav>

    <div class="row">

        <div class="col">
            <h2>{{ element.name }}</h2>
        </div>

        <div class="col text-right text-secondary">
            {% if element.user == user %}
            Your element
            {% else %}
            {{ element.user.login }}'s element
            {% endif %}
        </div>

    </div>

    <div class="text-secondary mb-3">
        <i>{{ element.description|default:'' }}</i>
    </div>

    {% with history=page_objects %}

    {% if element.type == 'number' %}
    {% include 'elements/views/number.html' %}

    {% elif element.type == 'text' %}
    {% include 'elements/views/text.html' %}

    {% elif element.type == 'gps' %}
    {% include 'elements/views/gps.html' %}

    {% else %}
    {% include 'elements/views/default.html' %}

    {% endif %}

    {% endwith %}

    {% include 'paginator.html' %}

</div>

{% endblock %}

registry/www/templates/elements/user_element_form.html
<div class="form-group {% if form.name.errors %}has-error{% endif %}">
    {{ form.name }}
    {% if form.name.errors %}
    <ul class="list-unstyled">
        {% for error in form.name.errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>

<div class="form-group {% if form.type.errors %}has-error{% endif %}">
    {{ form.type }}
    {% if form.type.errors %}
    <ul class="list-unstyled">
        {% for error in form.type.errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>

<div class="form-group {% if form.description.errors %}has-error{% endif %}">
    {{ form.description }}
    {% if form.description.errors %}
    <ul class="list-unstyled">
        {% for error in form.description.errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>

<div class="form-group {% if form.is_public.errors %}has-error{% endif %}">
    {{ form.is_public }}
    <label for="id_is_public">Public</label>
    {% if form.is_public.errors %}
    <ul class="list-unstyled">
        {% for error in form.is_public.errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>