registry/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('registry.www.urls')),
    path('api/', include('registry.api.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

registry/www/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('elements/', views.element_list_view, name='element_list'),

    # create elements
    path('elements/create/', views.element_create_view, name='create_element'),

    # edit elements
    path('elements/<element_name>/edit/', views.element_edit_view, name='edit_element'),

    # history
    path('<login>/elements/<element_name>/history/', views.history, name='history'),

    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

registry/core/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser

from django.core import validators
from django.db import models


class CreatedUpdated(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class UserManager(BaseUserManager):
    use_in_migrations = True


class User(AbstractBaseUser, CreatedUpdated):
    """
    Our custom user
    """
    login = models.CharField(max_length=30, unique=True, null=True, validators=[validators.validate_slug])
    first_name = models.CharField(max_length=30, blank=True, null=True)
    last_name = models.CharField(max_length=30, blank=True, null=True)
    email = models.EmailField(null=True, blank=True, unique=True)

    USERNAME_FIELD = 'login'
    objects = UserManager()

    class Meta:
        db_table = 'core_user'
        managed = True


class UserElement(CreatedUpdated):
    TYPE_CHOICES = (
        ('number', 'Number'),
        ('text', 'Text'),
        ('bool', 'Bool'),
        ('gps', 'GPS'),
    )
    name = models.CharField(max_length=30, null=False, blank=False, validators=[validators.validate_slug])
    type = models.CharField(max_length=30, choices=TYPE_CHOICES, null=False, blank=False)
    description = models.CharField(max_length=128, null=True, blank=True)
    user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='elements')
    is_public = models.BooleanField(default=False)

    class Meta:
        db_table = 'core_user_elements'
        managed = True
        unique_together = ['user', 'name']


class ElementNumber(CreatedUpdated):
    """
    Stores Numeric values
    """
    value = models.FloatField(blank=False, default=0)
    comment = models.TextField(null=True, blank=True)
    user_element = models.ForeignKey('UserElement', on_delete=models.CASCADE, related_name='number_values')

    class Meta:
        db_table = 'core_element_number'
        ordering = ['-created']

    def data(self):
        return {
            'value': self.value,
        }



class ElementText(CreatedUpdated):
    """
    Stores Textual values
    """
    value = models.TextField(null=True, blank=True, default='')
    comment = models.TextField(null=True, blank=True)
    user_element = models.ForeignKey('UserElement', on_delete=models.CASCADE, related_name='text_values')

    class Meta:
        db_table = 'core_element_text'
        ordering = ['-created']

    def data(self):
        return {
            'value': self.value,
        }


class ElementBool(CreatedUpdated):
    """
    Stores Boolean values
    """
    value = models.BooleanField(null=False, blank=False)
    comment = models.TextField(null=True, blank=True)
    user_element = models.ForeignKey('UserElement', on_delete=models.CASCADE, related_name='bool_values')

    class Meta:
        db_table = 'core_element_bool'
        ordering = ['-created']

    def data(self):
        return {
            'value': self.value,
        }


class ElementGPS(CreatedUpdated):
    """
    Stores Longitude and Latitude
    """
    longitude = models.CharField(max_length=50, null=False, blank=False)
    latitude = models.CharField(max_length=50, null=False, blank=False)
    comment = models.TextField(null=True, blank=True)
    user_element = models.ForeignKey('UserElement', on_delete=models.CASCADE, related_name='gps_values')

    class Meta:
        db_table = 'core_element_gps'
        ordering = ['-created']

    def data(self):
        return {
            'longitude': self.longitude,
            'latitude': self.latitude,
        }

registry/www/models.py
from django.db import models

# Create your models here.

registry/www/forms.py
from django import forms

import registry.core.models as core_models


class CreateElementForm(forms.ModelForm):
    class Meta:
        model = core_models.UserElement
        fields = ['name', 'type', 'description', 'is_public']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name'}),
            'type': forms.Select(choices=model.TYPE_CHOICES, attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Description'}),
        }


class EditElementForm(forms.ModelForm):
    class Meta:
        model = core_models.UserElement
        fields = ['name', 'description', 'is_public']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name'}),
            'description': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Description'}),
        }


class FilterElementsForm(forms.Form):
    name = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control mb-2 mr-2', 'placeholder': 'Name or description'}))

    CHOICES = (('', 'All'),) + core_models.UserElement.TYPE_CHOICES

    type = forms.ChoiceField(required=False, choices=CHOICES,
                             widget=forms.Select(attrs={'class': 'form-control mb-2 mr-sm-2'}))


class ElementTextForm(forms.ModelForm):
    class Meta:
        model = core_models.ElementText
        fields = ['value', 'comment']
        widgets = {
            'value': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Value'}),
            'comment': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Comment'}),
        }


class ElementNumberForm(forms.ModelForm):
    class Meta:
        model = core_models.ElementNumber
        fields = ['value', 'comment']
        widgets = {
            'value': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Value'}),
            'comment': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Comment'}),
        }


class ElementBoolForm(forms.ModelForm):
    class Meta:
        model = core_models.ElementBool
        fields = ['value', 'comment']
        widgets = {
            'value': forms.Select(attrs={'class': 'form-control'}),
            'comment': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Comment'}),
        }


class ElementGPSForm(forms.ModelForm):
    class Meta:
        model = core_models.ElementGPS
        fields = ['latitude', 'longitude', 'comment']
        widgets = {
            'latitude': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Latitude'}),
            'longitude': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Longitude'}),
            'comment': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Comment'}),
        }

registry/www/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.db import IntegrityError
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404

from registry.core import models as core_models
from . import forms


@login_required(login_url='login')
def home_view(request):
    return redirect(element_list_view)


@login_required(login_url='login')
def element_list_view(request):
    context = {}

    user_elements = core_models.UserElement.objects.filter(user=request.user)

    form = forms.FilterElementsForm(request.GET or None)
    context['form'] = form

    if form.is_valid():
        search = form.cleaned_data.get('name')
        element_type = form.cleaned_data.get('type')

        if search:
            user_elements = user_elements.filter(Q(name__icontains=search) | Q(description__icontains=search))

        if element_type:
            user_elements = user_elements.filter(type=element_type)

    context['user_elements'] = user_elements

    return render(request, 'elements/element_list.html', context)


@login_required(login_url='login')
def element_create_view(request):
    context = {}
    form = forms.CreateElementForm(request.POST or None)
    if form.is_valid():
        user_element = form.save(commit=False)
        user_element.user = request.user
        try:
            user_element.save()
        except IntegrityError:
            messages.error(request, 'Element with the same name and type already exists!')
            return redirect(element_create_view)

        messages.success(request, 'Element created!')
        return redirect(element_list_view)

    context['form'] = form

    return render(request, 'elements/create_element.html', context)


@login_required(login_url='login')
def element_edit_view(request, element_name):
    context = {}
    element = get_object_or_404(core_models.UserElement, name=element_name, user=request.user)
    context['element'] = element

    form = forms.EditElementForm(instance=element)

    if request.POST:
        action = request.POST.get('action')

        if action == 'update':
            form = forms.EditElementForm(request.POST, instance=element)
            if form.is_valid():
                form.save()
                messages.success(request, 'Element updated!')
                return redirect(element_edit_view, element_name=element.name)

        elif action == 'delete':
            element.delete()
            messages.success(request, 'Element deleted!')
            return redirect(element_list_view)

    context['form'] = form

    return render(request, 'elements/edit_element.html', context)


@login_required(login_url='login')
def history(request, login, element_name):

    context = {}

    if request.user.login == login:
        element = get_object_or_404(core_models.UserElement, name=element_name, user=request.user)
    else:
        element = get_object_or_404(core_models.UserElement, name=element_name, user__login=login, is_public=True)

    models = {
        'number': core_models.ElementNumber,
        'text': core_models.ElementText,
        'bool': core_models.ElementBool,
        'gps': core_models.ElementGPS,
    }

    model = models.get(element.type)
    if not model:
        raise Http404('Unknown Element Type')

    all_history = model.objects.filter(user_element=element).order_by('-created')
    context['element'] = element

    paginator = Paginator(all_history, 30)
    page = request.GET.get('page', 1)
    context['page_objects'] = paginator.get_page(page)
    context['paginator'] = paginator

    using_forms = {
        'number': forms.ElementNumberForm,
        'text': forms.ElementTextForm,
        'bool': forms.ElementBoolForm,
        'gps': forms.ElementGPSForm,
    }

    using_form = using_forms.get(element.type)
    context['form'] = using_form()

    if request.POST:
        action = request.POST.get('action')

        if action == 'add_value':
            using_form = using_forms.get(element.type)
            form = using_form(request.POST)
            if form.is_valid():
                form.instance.user_element = element
                form.save()
                messages.success(request, 'Value added')
                return redirect(history, request.user, element.name)


    return render(request, 'elements/history.html', context)


def login_view(request):
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(home_view)
        return redirect(login_view)
    return render(request, 'login.html')


def logout_view(request):
    logout(request)
    return redirect(login_view)

registry/www/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}" crossorigin="anonymous">

    <!-- Custom App Styles -->
    <link rel="stylesheet" href="{% static 'css/master.css' %}">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'font-awesome/css/all.css' %}" crossorigin="anonymous">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>

    <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>

    <title>{% block title %}Some page{% endblock %} | Registry</title>
  </head>
  <body>

    {% include 'navbar.html' %}

    {% include 'messages.html' %}

    {% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'jquery/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>

  </body>
</html>

registry/www/templates/login.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <title>Login | Registry</title>
</head>
<body>


<div class="container">

    <div class="row mt-5">

        <div class="col-md-4"></div>

        <div class="col-md-4 text-center">
            
            <img style="width: 20%;" class="mb-4" src="{% static 'img/square_logo.png' %}">

            <h3 class="mb-4">Please, log in</h3>

            <form method="POST">

                {% csrf_token %}

                <div class="form-group">
                    <input type="text" name="username" class="form-control form-control-lg" id="id_login" placeholder="Enter your login">
                </div>
                <div class="form-group">
                    <input type="password" name="password" class="form-control form-control-lg" placeholder="Password">
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary form-control">Log in!</button>
                </div>
            </form>
        </div>

        <div class="col-md-4"></div>

    </div>

</div>

</body>
</html>

registry/www/templates/messages.html
{% if messages %}
{% for message in messages %}
<div class="container-fluid">
    <div class="{% if message.tags %}{{ message.tags }}{% endif %} alert alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>
{% endfor %}
{% endif %}

registry/www/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
  <a class="navbar-brand" href="/">Registry</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>

  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ user }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        </div>
      </li>
    </ul>

  </div>
</nav>

registry/www/templates/paginator.html
{% if paginator.num_pages > 1 %}
    <div class="float-right">
        <nav>
            <ul class="pagination">

                {% if page_objects.has_previous %}
                    <li class="page-item">
                        <a href="?page=1" class="page-link {% if not page_objects.has_previous %}disabled{% endif %}">First </a>
                    </li>
                    <li class="page-item">
                        <a href="?page={{ page_objects.previous_page_number }}" class="page-link">Prev</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a href="?page=1" class="page-link">First</a>
                    </li>
                    <li class="page-item disabled">
                        <a href="#" class="page-link">Prev</a>
                    </li>

                {% endif %}

                <li class="page-item disabled">
                    <a href="#" class="page-link">{{ page_objects.number }} of {{ paginator.num_pages }}</a>
                </li>

                {% if page_objects.has_next %}
                    <li class="page-item">
                        <a href="?page={{ page_objects.next_page_number }}" class="page-link">Next</a>
                    </li>
                    <li class="page-item">
                        <a href="?page={{ page_objects.paginator.num_pages }}" class="page-link">Last</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a href="#" class="page-link">Next</a>
                    </li>
                    <li class="page-item disabled">
                        <a href="#" class="page-link">Last</a>
                    </li>

                {% endif %}

            </ul>

    </div>
{% endif %}